

== Red Hat CodeReady Containers (Minishift equivalent for OpenShift 4.1 or newer)

== Draft lab guide showing how to set up CodeReady Containers, Ansible Agnostic Deployer and OpenDataHub on a RHEL 8.1 physical server

*Red Hat CodeReady Containers* brings a minimal OpenShift 4.1 or newer cluster to your local computer
(see https://code-ready.github.io/crc/)

*Ansible Agnostic Deployer* aka AgnosticD, is a fully automated 2 Phase deployer for building and deploying everything from basic infrastructure to fully configured running application environments running on either public Cloud Providers or OpenShift clusters.

AgnosticD is not an OpenShift Deployer, though it can and does that, it is however also a deployer that just happens to be used to deploy a lot of OpenShift and OpenShift workloads, amongst other things. See https://github.com/redhat-cop/agnosticd

*Open Data Hub* is a machine-learning-as-a-service platform built on Red Hat's Kubernetes-based OpenShift® Container Platform, Ceph Object Storage, and Kafka/Strimzi integrating a collection of open source projects. See https://opendatahub.io/




The instructions below cover

- installing Red Hat CodeReady Containers on a RHEL 8.1 *physical* server 

- using Ansible Agnostic Deployer to deploy OpenDataHub on OpenShift 4.1

- configuring SSH tunneling / port forwarding to access the OpenShift console, OpenDataHub etc from your laptop.




[marc@dell-r730-019 ~]$ cat /etc/redhat-release

----
Red Hat Enterprise Linux release 8.1 Beta (Ootpa)
----

== Install packages

su -c 'dnf -y install git wget tar qemu-kvm libvirt NetworkManager jq'

sudo systemctl start libvirtd

sudo systemctl enable libvirtd


== Install Python

See https://developers.redhat.com/blog/2019/05/07/what-no-python-in-red-hat-enterprise-linux-8/

yum install @python36

yum install @python27

When you install either (or both) you can easily make 
/usr/bin/python point to the right place using alternatives --config python

[root@dell-r730-019 ~]#  alternatives --config python

----
There are 3 programs which provide 'python'.

  Selection    Command
*+ 1           /usr/libexec/no-python
   2           /usr/bin/python2
   3           /usr/bin/python3
----
Choose 3 

[marc@dell-r730-019 ansible]$ python -V

----

Python 3.6.8

----


== Add user

adduser marc

passwd marc

usermod -aG wheel marc

== Install Go

cd /home/marc

wget https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz

tar -xzf go1.12.9.linux-amd64.tar.gz

Add to .bashrc:

----
export GOROOT=/home/marc/go

export GOPATH=/home/marc/work

export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
----

source .bashrc

== Install CodeReady Containers

su marc

cd /home/marc

git clone https://github.com/code-ready/crc.git

cd crc

make

Set the memory available to CRC according to what you have on your physical server

I’m on a physical server with around 100G of memory so I allocate 80G to CRC as follows:

[marc@dell-r730-019 ansible]$ crc config set memory 81920

[marc@dell-r730-019 crc]$ crc setup



== Download CodeReady Containers bundle

(crc_libvirt_4.1.11.crcbundle in my case)


== Install CodeReady Containers

You'll need your pull secret from https://cloud.redhat.com/openshift/install/metal/user-provisioned



[marc@dell-r730-019 crc]$ crc start -b crc_libvirt_4.1.11.crcbundle

----
INFO To access the cluster using 'oc', run 'eval $(crc oc-env) && oc login -u kubeadmin -p <password> https://api.crc.testing:6443' ******INFO Access the OpenShift web-console here: https://console-openshift-console.apps-crc.testing ********************************************************INFO Login to the console with user: kubeadmin, password: 78UVa-zNj5W-YB62Z-ggxGZ *********************************************************************CodeReady Containers instance is running
----


cd /home/marc/crc

eval $(crc oc-env) && oc login -u kubeadmin -p <password> https://api.crc.testing:6443

oc get projects


== Install the Ansible Agnostic Deployer

cd /home/marc

git clone https://github.com/redhat-cop/agnosticd.git

cd agnosticd/ansible


sudo python -m pip install --upgrade --trusted-host files.pythonhosted.org -r requirements.txt

sudo python3 -m pip install --upgrade --trusted-host files.pythonhosted.org -r requirements.txt

sudo pip3 install kubernetes

sudo pip3 install openshift


== Deploy OpenDataHub

[marc@dell-r730-019 ansible]$ cat inventory

----
127.0.0.1 ansible_connection=local
----

export WORKLOAD="ocp4-workload-open-data-hub"

ansible-playbook -i inventory  ./configs/ocp-workloads/ocp-workload.yml -e"ocp_workload=${WORKLOAD}" -e"ACTION=create" -e"user_count=1" -e"ocp_username=kubeadmin" -e"ansible_become_pass=<password>" -e"silent=False"

== Test OpenDataHub

[marc@dell-r730-019 ansible]$ oc project open-data-hub-user1

[marc@dell-r730-019 crc]$ oc get pods

----
NAME                                                         READY   STATUS      RESTARTS   AGE
jupyterhub-1-7q4zs                                           1/1     Running     0          49m
jupyterhub-1-deploy                                          0/1     Completed   0          49m
jupyterhub-db-1-deploy                                       0/1     Completed   0          49m
jupyterhub-db-1-rttgz                                        1/1     Running     1          49m
jupyterhub-nb-c455c922-2d4e64-2d4d66-2db463-2d066ac236166f   1/1     Running     0          28m
opendatahub-operator-86c5cb8b4b-l5cg6                        1/1     Running     0          50m
spark-operator-6b46b4d97-8mv92                               1/1     Running     0          49m
----


[marc@dell-r730-019 crc]$ oc get route

----
NAME         HOST/PORT                                         PATH   SERVICES     PORT       TERMINATION     WILDCARD
jupyterhub   jupyterhub-open-data-hub-user1.apps-crc.testing          jupyterhub   8080-tcp   edge/Redirect   None
----


On your laptop, add jupyterhub-open-data-hub-user1.apps-crc.testing to your /etc/hosts. Example:

----
127.0.0.1	localhost marc.rhel8 console-openshift-console.apps-crc.testing oauth-openshift.apps-crc.testing mapit-app-management.apps-crc.testing mapit-spring-pipeline-demo.apps-crc.testing jupyterhub-open-data-hub-user1.apps-crc.testing jupyterhub-open-data-hub-user1.apps-crc.testing
----

On your laptop, sudo ssh marc@dell-r730-019 -L 443:jupyterhub-open-data-hub-user1.apps-crc.testing:443

You can now browse to https://jupyterhub-open-data-hub-user1.apps-crc.testing

