


== Tekton Pipeline with Sysdig Secure image scans on OpenShift 4.2+


See video showing Tekton Pipeline with Sysdig Secure image scans on OpenShift 4.2+ at https://youtu.be/eDk5CgWko18


Prerequisites: OpenShift 4.2+

I'm using CodeReady Containers:

----
oc version && crc version
Client Version: v4.3.0
Server Version: 4.2.0
Kubernetes Version: v1.14.6+2e5ed54
crc version: 1.0.0+575079b
OpenShift version: 4.2.0 (embedded in binary)
----

== Install Tekton Pipelines

----
oc new-project tekton-pipelines
oc adm policy add-scc-to-user anyuid -z tekton-pipelines-controller
oc apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.notags.yaml
----

== Check Tekton is successfully installed

----
oc get pods
NAME                                           READY   STATUS    RESTARTS   AGE
tekton-pipelines-controller-669dfb5dd4-9vkvl   1/1     Running   0          11s
tekton-pipelines-webhook-5669b89c9c-4nrhw      1/1     Running   0          11s
----

Download the following Tekton Pipelines 

Both include Sysdig Secure scan steps; the first for an image where no vulns should be found, the second one for an image with vulns

Replace the value of SYSDIG_SECURE_TOKEN in both files

----
wget https://raw.githubusercontent.com/marcredhat/crcdemos/master/sysdig/sysdigpipeline.yaml
wget https://raw.githubusercontent.com/marcredhat/crcdemos/master/sysdig/sysdigpipelineblock.yaml
----

oc create   -f sysdigpipeline.yaml

oc get pods
----
NAME                                                       READY   STATUS    RESTARTS   AGE
demo-pipeline-run-1-skaffold-unit-tests-2b7kj-pod-6423ad   1/3     Running   0          32s
tekton-pipelines-controller-669dfb5dd4-9vkvl               1/1     Running   0          8m51s
tekton-pipelines-webhook-5669b89c9c-4nrhw                  1/1     Running   0          8m51s
----

== Check what happens during the Sysdig secure scan step

oc logs demo-pipeline-run-1-skaffold-unit-tests-2b7kj-pod-6423ad -c step-scan

----
env var $TIMEOUT not defined, defaulting to 10 minutes
Adding image docker.io/alpine to Anchore engine at https://secure.sysdig.com/api/scanning/v1/anchore
Image digest: sha256:e4355b66995c96b4b468159fc5c7e3540fcef961189ca13fee877798649f531a
Waiting for analysis to complete
Analysis complete
Image Digest: sha256:e4355b66995c96b4b468159fc5c7e3540fcef961189ca13fee877798649f531a
Full Tag: docker.io/alpine:latest
Status: pass
Last Eval: 2019-10-24T03:28:01Z
Policy ID: default
----

Now let's see what happens with an image with vulns

----
oc delete -f sysdigpipeline.yaml
oc create -f sysdigpipelineblock.yaml
----

oc get pods

----
NAME                                                       READY   STATUS    RESTARTS   AGE
demo-pipeline-run-1-skaffold-unit-tests-fwxcx-pod-679ab1   1/3     Running   0          25s
tekton-pipelines-controller-669dfb5dd4-9vkvl               1/1     Running   0          12m
tekton-pipelines-webhook-5669b89c9c-4nrhw                  1/1     Running   0          12m
----

oc logs demo-pipeline-run-1-skaffold-unit-tests-fwxcx-pod-679ab1 -c step-scan

----
env var $TIMEOUT not defined, defaulting to 10 minutes
Adding image quay.io/marcf5/mltitanic to Anchore engine at https://secure.sysdig.com/api/scanning/v1/anchore
Image digest: sha256:6ceaa66e80586fca952eaa6436ce7497a476a4556272eff6da679eb79d142a09
Waiting for analysis to complete
Analysis complete
Image Digest: sha256:6ceaa66e80586fca952eaa6436ce7497a476a4556272eff6da679eb79d142a09
Full Tag: quay.io/marcf5/mltitanic:latest
Status: fail
Last Eval: 2019-10-23T23:32:53Z
Policy ID: default
----

== Example scanning after building image

For an example that uses a service account with specific permissions to deploy to the namespace, and a pipeline that first builds and pushes the image to registry, and then scan each image using Sysdig Secure, use sysdigpipeline2.yaml and sysdigpipeline2block.yaml.

You will need to do some modifications to the files:

* At the beginning, replace `<username>` and `<password>` with your Docker Hub or Google Registry credentials.
* Replace `<your_sysdig_secure_token>` with your Sysdig API token
* Replace the destination url of the built images to one available in your registry, at:
  * `gcr.io/christiewilson-catfactory/leeroy-web`
  * `gcr.io/christiewilson-catfactory/leeroy-web`
If you use docker for those registries, start the URL with `index.docker.io`

oc create   -f sysdigpipeline2.yaml

Wait until the pipeline finishes running.

oc get pods

```
NAME                                                      READY   STATUS      RESTARTS   AGE
demo-pipeline-run-1-build-skaffold-app-nf42x-pod-fwxrs    0/4     Completed   0          14m
demo-pipeline-run-1-build-skaffold-web-gz6cm-pod-wrd47    0/4     Completed   0          14m
demo-pipeline-run-1-deploy-app-nzv88-pod-9c2mw            0/3     Completed   0          10m
demo-pipeline-run-1-deploy-web-xgmmw-pod-6b4ml            0/3     Completed   0          10m
demo-pipeline-run-1-scan-image-app-cbc2r-pod-qfj6x        0/1     Completed   0          12m
demo-pipeline-run-1-scan-image-web-c97ct-pod-hmfl7        0/1     Completed   0          12m
demo-pipeline-run-1-skaffold-unit-tests-qrf2j-pod-5l8qh   0/2     Completed   0          16m
leeroy-app-7564dffd66-vdgjm                               1/1     Running     0          10m
leeroy-web-546778548d-5th9c                               1/1     Running     0          10m
tekton-pipelines-controller-dcf84f645-rtvcg               1/1     Running     0          59m
tekton-pipelines-webhook-74d55ccdcf-bmhww                 1/1     Running     0          59m
```









