== Red Hat CodeReady Containers (Minishift equivalent for OpenShift 4.1 or newer)

== Draft lab guide showing how to set up the following on a Fedora 30 physical server:



- CodeReady Containers / OpenShift 4.1

- Ansible Agnostic Deployer

- OpenDataHub

- Process Automation Manager

- Change Data Capture with Debezium and Kafka

- Tekton Pipelines


*Youtube playlist at https://www.youtube.com/playlist?list=PLg1pvyPzFye2UtQjZTSjoXhFdqkGK6exw*

*Red Hat CodeReady Containers* brings a minimal OpenShift 4.1 or newer cluster to your local computer
(see https://code-ready.github.io/crc/)

*Ansible Agnostic Deployer* aka AgnosticD, is a fully automated 2 Phase deployer for building and deploying everything from basic infrastructure to fully configured running application environments running on either public Cloud Providers or OpenShift clusters.

AgnosticD is not an OpenShift Deployer, though it can and does that, it is however also a deployer that just happens to be used to deploy a lot of OpenShift and OpenShift workloads, amongst other things. See https://github.com/redhat-cop/agnosticd

*Open Data Hub* is a machine-learning-as-a-service platform built on Red Hat's Kubernetes-based OpenShift® Container Platform, Ceph Object Storage, and Kafka/Strimzi integrating a collection of open source projects. See https://opendatahub.io/




The instructions below cover

- installing Red Hat CodeReady Containers on a Fedora 30  *physical* server

- using Ansible Agnostic Deployer to deploy OpenDataHub on OpenShift 4.1

- configuring SSH tunneling / port forwarding to access the OpenShift console, OpenDataHub etc from your laptop.



[marc@fedora30 ~]$ cat /etc/fedora-release

----
Fedora release 30 (Thirty)
----



== Install packages

dnf config-manager --set-enabled fedora

su -c 'dnf -y install git wget tar qemu-kvm libvirt NetworkManager jq libselinux-python'

sudo systemctl start libvirtd

sudo systemctl enable libvirtd


== Check Python is installed
See https://developer.fedoraproject.org/tech/languages/python/multiple-pythons.html

python3 --version

----
Python 3.7.4
----

Create a Python virtual environment; we will use it later when we set up Ansible Agnostic Deployer.

----
python3 -m venv agnosticd
----


== Add user

sudo adduser demouser

sudo passwd demouser

sudo usermod -aG wheel demouser


== Install Go

su demouser

cd /home/demouser

wget https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz

tar -xzf go1.12.9.linux-amd64.tar.gz

Add to .bashrc:

----
export GOROOT=/home/demouser/go

export GOPATH=/home/demouser/work

export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
----

source .bashrc

go

== Install CodeReady Containers

wget https://mirror.openshift.com/pub/openshift-v4/clients/crc/1.0.0-beta.3/crc-linux-amd64.tar.xz
or
https://mirror.openshift.com/pub/openshift-v4/clients/crc/1.0.0-beta.3/crc_virtualbox_4.1.11.crcbundle


tar -xvf crc-linux-amd64.tar.xz

cd crc-linux-1.0.0-beta.3-amd64/

sudo cp ./crc /usr/bin

Set the memory available to CRC according to what you have on your physical server

I’m on a physical server with around 100G of memory so I allocate 80G to CRC as follows:

----
crc config set memory 81920
----


crc setup

----
INFO Checking if NetworkManager is installed
INFO Checking if NetworkManager service is running
INFO Caching oc binary
INFO Setting up virtualization
INFO Setting up KVM
INFO Installing libvirt service and dependencies
INFO Adding user to libvirt group
INFO Enabling libvirt
INFO Starting libvirt service
INFO Installing crc-driver-libvirt
INFO Removing older system-wide crc-driver-libvirt
INFO Setting up libvirt 'crc' network
INFO Starting libvirt 'crc' network
INFO Writing Network Manager config for crc
INFO Writing dnsmasq config for crc
INFO Unpacking bundle from the CRC binary
----


You'll need your pull secret from https://cloud.redhat.com/openshift/install/metal/user-provisioned


crc start

----
INFO Checking if NetworkManager is installed
INFO Checking if NetworkManager service is running
INFO Checking if oc binary is cached
INFO Checking if Virtualization is enabled
INFO Checking if KVM is enabled
INFO Checking if libvirt is installed
INFO Checking if user is part of libvirt group
INFO Checking if libvirt is enabled
INFO Checking if libvirt daemon is running
INFO Checking if crc-driver-libvirt is installed
INFO Checking if libvirt 'crc' network is available
INFO Checking if libvirt 'crc' network is active
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists
INFO Checking if CRC bundle is cached in '$HOME/.crc'
? Image pull secret [? for help]
----


----
INFO To access the cluster using 'oc', run 'eval $(crc oc-env) && oc login -u kubeadmin -p <password> https://api.crc.testing:6443' ******INFO Access the OpenShift web-console here: https://console-openshift-console.apps-crc.testing ********************************************************
INFO Login to the console with user: kubeadmin, password: <password>
----


